name: flexibility_test
description: Configuration optimized for cognitive flexibility experiments
model:
  input_size: 64
  output_size: 4
  layer_configs:
  - base_population_size: 32
    neuron_pool_size: 64
    output_size: 16
    initial_budget: 50.0
    budget_decay_rate: 0.005
    recruitment_threshold: 0.08
    population_activation: relu
    recurrent_strength: 0.15
    inhibition_strength: 0.05
    adaptation_rate: 0.01
    noise_level: 0.0
  global_budget_decay: 0.0
  inter_layer_connections: false
  use_global_feedback: true
  output_activation: none
training:
  learning_rate: 0.001
  batch_size: 16
  num_epochs: 100
  optimizer: adam
  weight_decay: 0.0001
  recruitment_loss_weight: 0.05
  flexibility_loss_weight: 0.2
  connectivity_loss_weight: 0.02
  budget_regularization: 0.005
  budget_decay_schedule: linear
  recruitment_warmup_epochs: 5
  flexibility_ramp_epochs: 30
  early_stopping: true
  patience: 15
  min_delta: 0.001
dataset_type: task_switching
data_params:
  task_types:
  - classification
  - regression
  - sequence
  switch_probability: 0.3
  sequence_length: 100
  num_sequences: 50
  task_difficulty: medium
track_connectivity: true
track_flexibility: true
analysis_frequency: 5
autism_modeling: false
baseline_comparison: true
baseline_models:
- mlp
- lstm
- transformer
save_results: true
output_dir: results/flexibility
plot_results: true
